services:
  - type: web
    name: keepfresh-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: gunicorn my_web_server.app:app
    envVars:
      - key: SQLALCHEMY_DATABASE_URI
        fromEnvVar: SQLALCHEMY_DATABASE_URI
