services:
  - type: web
    name: keepfresh-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 my_web_server/app.py"
    envVars:
      - key: DATABASE_URL
        value: sqlite:///instance/keepfresh.db
